#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

domain_information () {
    # Fetch DNS record information using dig and process the output
    local record_info
    record_info=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')

    # Check if the record_info is not empty
    if [ -n "$record_info" ]; then
        echo "$2 $record_info" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
    else
        echo "No DNS record found for the subdomain $2.$1"
    fi
}

case "$#" in
    1)
        domain_information "$1" "www"
        domain_information "$1" "lb-01"
        domain_information "$1" "web-01"
        domain_information "$1" "web-02"
        ;;
    2)
        domain_information "$1" "$2"
        ;;
    *)
        echo "Usage: ./1-world_wide_web <domain> [subdomain]"
        exit 1
        ;;
esac
