#!/usr/bin/env bash
# Install Nginx web server and create an HTML page

# Update package list
apt-get -y update

# Install Nginx
apt-get install -y nginx

# Create an HTML page with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx without using systemctl
service nginx restart
