#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect the above requirements

# Update package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create the index.html file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html

# Add redirection in the nginx default server block
sudo sed -i '/server_name _;/a\\n    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-enabled/default

# Restart nginx to apply the changes
sudo service nginx restart
