#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect the requirements:
# 1. Install nginx web server
# 2. Serve a page with "Hello World!" content at the root
# 3. Redirect /redirect_me to a specific URL

# Update the package list
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Create the index.html file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html

# Add redirection in the nginx default server block
string_for_replacement="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.blog.ehoneahobed.com;\n\t}"
sudo sed -i "s|server_name _;|$string_for_replacement|" /etc/nginx/sites-available/default

# Restart nginx to apply the changes
sudo service nginx restart
