#!/bin/bash

# Define the name of the private key
KEY_NAME="school"

# Define the number of bits for the key
KEY_BITS=4096

# Define the passphrase
PASSPHRASE="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $KEY_BITS -f $KEY_NAME -N $PASSPHRASE
